# Generated by Django 6.1.1 on 2026-09-16 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maktab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('honalar', models.IntegerField()),
                ('elektronika', models.CharField(max_length=150)),
                ('zona', models.CharField(max_length=300)),
                ('talim', models.CharField(choices=[('yaxshi', 'yaxshi'), ('orta', 'orta'), ('yomon', 'yomon')], max_length=10)),
                ('direktor', models.CharField(max_length=50)),
                ('oqtuvchilar', models.IntegerField()),
                ('oquvchilar', models.IntegerField()),
                ('manzil', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Oquvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alochilar_soni', models.IntegerField()),
                ('ism_familiya', models.CharField(max_length=40)),
                ('manzil', models.CharField(max_length=20)),
                ('davomat', models.CharField(choices=[('KEL', 'KELDI'), ('KEM', 'KEMADI'), ('SAB', 'SABABLI')], default='KEL', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Sinf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('dars_vaqti', models.CharField(max_length=50)),
                ('sharoyit', models.CharField(max_length=100)),
                ('xona_kengligi', models.PositiveIntegerField()),
                ('yonalish', models.CharField(max_length=50)),
                ('oqituvchi', models.CharField(max_length=25)),
                ('orindiqlar', models.PositiveIntegerField()),
                ('oquvchilar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.oquvchi')),
            ],
        ),
    ]
