# Generated by Django 6.1.1 on 2026-09-21 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.oquvchi')),
            ],
        ),
    ]
